# Generated by Django 4.0.4 on 2022-04-27 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название полки')),
                ('size', models.PositiveIntegerField(verbose_name='Размер')),
                ('space', models.JSONField(verbose_name='Пространство для серверов')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Полка',
                'verbose_name_plural': 'Полки',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Метка сервера')),
                ('length', models.PositiveIntegerField(verbose_name='Размер')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('rack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rack.rack')),
            ],
            options={
                'verbose_name': 'Сервер',
                'verbose_name_plural': 'Серверы',
            },
        ),
    ]
