# Generated by Django 4.0.4 on 2022-04-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rack', '0002_remove_rack_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rack',
            options={'verbose_name': 'Стойка', 'verbose_name_plural': 'Стойки'},
        ),
        migrations.AddField(
            model_name='server',
            name='color',
            field=models.CharField(default=1, max_length=50, verbose_name='Цвет'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rack',
            name='size',
            field=models.PositiveIntegerField(help_text='Размер измеряется в целых юнитах', verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название стойки'),
        ),
    ]
