# Generated by Django 3.2.15 on 2022-08-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rack', '0005_auto_20220825_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Заметки'),
        ),
    ]
