# Generated by Django 3.2.15 on 2022-08-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rack', '0006_rack_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='backside',
            field=models.BooleanField(blank=True, null=True, verbose_name='Является задней стороной?'),
        ),
        migrations.AddField(
            model_name='rack',
            name='reverse_side',
            field=models.ManyToManyField(related_name='_rack_rack_reverse_side_+', to='rack.Rack', verbose_name='Обратная сторона стойки'),
        ),
    ]
