# Generated by Django 3.2.15 on 2022-09-01 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rack', '0007_auto_20220831_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.CharField(choices=[('10Mbit', '10Mbit'), ('100Mbit', '100Mbit'), ('1Gbit', '1Gbit'), ('10Gbit', '10Gbit')], max_length=20, verbose_name='Скорость связи')),
                ('port1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port1', to='rack.port')),
                ('port2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port2', to='rack.port')),
            ],
        ),
        migrations.AddField(
            model_name='port',
            name='link',
            field=models.ManyToManyField(related_name='_rack_port_link_+', through='rack.LinkPort', to='rack.Port'),
        ),
    ]
