# Generated by Django 3.2.15 on 2022-09-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rack', '0009_auto_20220902_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Позиция на сервере'),
        ),
    ]
