# Generated by Django 3.2.15 on 2022-09-11 18:27

from django.db import migrations, models


def forward_func(apps, schema_editor):
    Rack = apps.get_model("rack", "Rack")
    Server = apps.get_model("rack", "Server")
    racks = Rack.objects.all()
    servers = Server.objects.all()

    for rack in racks:
        space = rack.space
        position = 0

        for elem in space:
            if type(elem) == int:
                position += elem
            else:
                server = servers.get(pk=elem['id'])
                server.position = position
                position += elem['length']

    servers.bulk_update(servers, ['position'], batch_size=50)


class Migration(migrations.Migration):

    dependencies = [
        ('rack', '0010_server_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='space',
            field=models.JSONField(null=True, verbose_name='Пространство для серверов'),
        ),
        migrations.RunPython(forward_func, migrations.RunPython.noop)
    ]
